In [70]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [71]:
'''Read about the movielens dataset and write down a summary of metadata.'''


'''- MovieLens is a movie rec service

- Dataset has 5 star ratings and free text activity

- 100,836 ratings (0.5-5 w/ 0.5 increments)

- 9742 movies

- 3683 tags

- Tags are user generated metadata about movies.Each contains single word or a short phrase.

- Users represented by ID (consistent b/w rating and tags)

- All selected users had rated atleast 20 movies.

- Movie ID consistent accross ratings, tags, movies and links

- Data is contained in files 'links.csv','movies.csv','ratings.csv','tags.csv'

- Genres pipe separated list'''

"- MovieLens is a movie rec service\n\n- Dataset has 5 star ratings and free text activity\n\n- 100,836 ratings (0.5-5 w/ 0.5 increments)\n\n- 9742 movies\n\n- 3683 tags\n\n- Tags are user generated metadata about movies.Each contains single word or a short phrase.\n\n- Users represented by ID (consistent b/w rating and tags)\n\n- All selected users had rated atleast 20 movies.\n\n- Movie ID consistent accross ratings, tags, movies and links\n\n- Data is contained in files 'links.csv','movies.csv','ratings.csv','tags.csv'\n\n- Genres pipe separated list"

In [72]:
df=pd.read_csv("ratings.csv")
movies=pd.read_csv("movies.csv")
tags=pd.read_csv("tags.csv")
links=pd.read_csv("links.csv")
df_1=pd.merge(df,movies,on='movieId')

In [73]:
''' Read the “ratings.csv” file and create a pivot table with index=‘userId’, columns=‘movieId’,
values = “rating.'''
pivot = df.pivot_table(index=['userId'], columns=['movieId'], values=['rating'])
pivot=pivot.fillna(0)
pivot

        rating                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10
userId
1          4.0    0.0    4.0    0.0    0.0    4.0    0.0    0.0    0.0    0.0
2          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
3          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
4          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
5          4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
606        2.5    0.0    0.0    0.0    0.0    0.0    2.5    0.0    0.0    0.0
607        4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
608        2.5    2.0    2.0    0.0    0.0    0.0    0.0    0.0    0.0    4.0
609        3.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    4.0
610        5.0    0.0    0.0    0.0    0.0    5.0    0.0    0.0    0.0    0.0

         ...                                                                 \
movieId  ... 193565 193567 193571 193573 193579 193581 193583 193585 193587
userId   ...
1        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
2        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
3        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
4        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
5        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
606      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
607      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
608      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
609      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
610      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0


movieId 193609
userId
1          0.0
2          0.0
3          0.0
4          0.0
5          0.0
...        ...
606        0.0
607        0.0
608        0.0
609        0.0
610        0.0

[610 rows x 9724 columns]

In [74]:
''' sklearn.metrics.pairwise_distances can be used to compute distance between all pairs of 
users. pairwise_distances() takes a metric parameter for what distance measure to use. Use 
cosine similarity for finding similarity among users. Use the following packages.'''
distance=pairwise_distances(pivot,metric="cosine")
x= pd.DataFrame(np.squeeze(distance))
x

,0,1,2,3,4,5,6,7,8,9,...,600,601,602,603,604,605,606,607,608,609
0,2.220446e-16,9.727171e-01,9.402797e-01,8.056052e-01,0.870920,0.871848,0.841256,0.863032,0.935737,0.983125,...,0.919446,0.835545,0.778514,0.929331,0.846375,0.835809,7.306108e-01,0.708903,0.906428,8.546792e-01
1,9.727171e-01,2.220446e-16,1.000000e+00,9.962741e-01,0.983386,0.974667,0.972415,0.972743,1.000000,0.932555,...,0.797329,0.983134,0.988003,1.000000,1.000000,0.971571,9.870521e-01,0.953789,0.972435,8.975732e-01
2,9.402797e-01,1.000000e+00,1.110223e-16,9.977486e-01,0.994980,0.996064,1.000000,0.995059,1.000000,1.000000,...,0.994952,0.995108,0.975008,1.000000,0.989306,0.987007,9.807532e-01,0.978872,1.000000,9.678813e-01
3,8.056052e-01,9.962741e-01,9.977486e-01,3.330669e-16,0.871341,0.911509,0.884880,0.937031,0.988639,0.968837,...,0.914062,0.871727,0.692027,0.947015,0.915416,0.799605,8.682538e-01,0.850142,0.967802,8.923170e-01
4,8.709201e-01,9.833856e-01,9.949803e-01,8.713411e-01,0.000000,0.699651,0.891658,0.570925,1.000000,0.969389,...,0.931952,0.581253,0.889852,0.741227,0.851242,0.893565,8.471340e-01,0.864465,0.738768,9.392082e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,8.358085e-01,9.715710e-01,9.870070e-01,7.996055e-01,0.893565,0.897877,0.799965,0.900612,0.924102,0.911037,...,0.821916,0.883466,0.699331,0.933968,0.851859,0.000000,8.469374e-01,0.737442,0.930378,7.988962e-01
606,7.306108e-01,9.870521e-01,9.807532e-01,8.682538e-01,0.847134,0.837818,0.813886,0.814858,0.988156,0.989549,...,0.907475,0.800090,0.796460,0.862166,0.881220,0.846937,2.220446e-16,0.716919,0.850810,8.608856e-01
607,7.089026e-01,9.537890e-01,9.788715e-01,8.501419e-01,0.864465,0.821191,0.676459,0.812767,0.899565,0.922576,...,0.841645,0.802486,0.767229,0.844694,0.821858,0.737442,7.169185e-01,0.000000,0.878007,6.779451e-01
608,9.064281e-01,9.724346e-01,1.000000e+00,9.678020e-01,0.738768,0.785766,0.909160,0.576007,1.000000,0.978234,...,0.964347,0.664769,0.938059,0.763399,0.902390,0.930378,8.508097e-01,0.878007,0.000000,9.467745e-01
609,8.546792e-01,8.975732e-01,9.678813e-01,8.923170e-01,0.939208,0.947332,0.806781,0.921847,0.925601,0.878928,...,0.777509,0.912472,0.836906,0.947448,0.880705,0.798896,8.608856e-01,0.677945,0.946775,2.220446e-16

In [75]:
'''Find the 5 most similar user for user with user Id 25'''
user_10=df['userId']==10
allusers=pivot.values
user_10=allusers[0]
den1=np.sqrt(sum([np.square(x) for x in user_10]))
cosinesim=[(10,1)]
i=1
for user in allusers[1:]:
    numer=[x*y for x,y in zip(user_10,user)]
    den2=np.sqrt(sum([np.square(x) for x in user]))
    costheta = sum(numer)/(den1*den2)
    cosinesim.append((pivot.index[i],costheta))
    i=i+1
cosinesim.sort(key=lambda x:x[1],reverse =True)
simusers=cosinesim[0:6]
simusers

[(10, 1),
 (266, 0.3574077096032742),
 (313, 0.3515615184909569),
 (368, 0.34512705158353046),
 (57, 0.3450342788075837),
 (91, 0.33472692041817076)]

In [76]:
'''Use the “movies” dataset to find out the names of movies, user 1 and user 338 have 
watched in common and how they have rated each one of them'''
movies = pd.read_csv('movies.csv')
movies
comm = pd.DataFrame(pd.merge(df, movies, on="movieId"))
u1 = pd.DataFrame(comm[comm["userId"] == 1][["title","rating"]])
u338 = pd.DataFrame(comm[comm["userId"] == 338][["title","rating"]])
df_2=pd.DataFrame(pd.merge(u1,u338))
df_2.head()

                              title  rating
0           Schindler's List (1993)     5.0
1  Silence of the Lambs, The (1991)     4.0

In [77]:
''' Use the movies dataset to find out the common movie names between user 2 and user 
338 with least rating of 4.0'''
u2=pd.DataFrame(comm[comm["userId"] == 2][["title","rating"]])
u338=pd.DataFrame(comm[comm["userId"] == 338][["title","rating"]])
df_3=pd.DataFrame(pd.merge(u2,u338))
df_4=df_3[df_3['rating']>=4.0]
df_4.head()

Empty DataFrame
Columns: [title, rating]
Index: []

In [ ]:
'''Item-Based Similarity'''
''' Find the top 5 movies which are similar to the movie “Godfather"'''
data_table = pd.pivot_table(df_1,values='rating',columns='title',index='userId').fillna(0)
print(data_table.corr()['Godfather, The (1972)'].sort_values(ascending=False).iloc[:6])